version: '3.7'

services:
  api:
    image: dnyf-group-api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./:/app
    networks:
      - dnyfnet
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dbuser
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
      - MYSQL_DATABASE=dnyf-group-db
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      dnyfnet:
        aliases:
        - dnyf-group-db

volumes:
  mysql:
  mysql_config:

networks:
  dnyfnet:
